version: "3.4"
x-common-variables: &influx-variables
  INFLUX_USER: admin
  INFLUX_PASSWORD: adminInflux!23
  INFLUX_DB: gatling

services:
  postgres:
    container_name: postgres_container
    image: postgres:13.3
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "gmonitoring"
      POSTGRES_USER: "gatlinguser"
      POSTGRES_PASSWORD: "gatlinguser1"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gatlinguser -d gmonitoring"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    user: root
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "gatlinguser@gatlinguser.com"
      PGADMIN_DEFAULT_PASSWORD: "gatlinguser1"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

  performance-management:
    container_name: performance-management
    image: ivanogn/performance-management:0.2.1
    ports:
      - "8081:80"
    volumes:
      - /PathToGatlingReportDir:/var/www/gatlingReport
    restart: unless-stopped

  influxdb:
    container_name: gatling-influxdb
    image: ivanogn/influx-gatling:0.0.18
    environment: *influx-variables
    ports:
      - '8086:8086'
      - '2003:2003'
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  grafana:
    container_name:  grafana-gatling
    image:  ivanogn/grafana-gatling:0.0.18
    environment:
      <<: *influx-variables
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: superAdmin!23
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config:/etc/grafana
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/share:/var/usr/share/grafana
      - ./grafana/share:/var/log/grafana

networks:
  postgres:
    driver: bridge

